wandb_version: 1

Architecture:
  desc: null
  value: LocallyConnected
BetSizeFactor:
  desc: null
  value: 0.34
EntropyLossCoefficient:
  desc: null
  value: 0.01
EnvType:
  desc: null
  value: stocks-v0
Epochs:
  desc: null
  value: 4
EpsClip:
  desc: null
  value: 0.1
Explanations:
  desc: null
  value: 10
FileName:
  desc: null
  value: EURUSD_M5.csv
Gamma:
  desc: null
  value: 0.99
Horizon:
  desc: null
  value: 45
Lambda:
  desc: null
  value: 0.99
LenMemory:
  desc: null
  value: 570
Leverage:
  desc: null
  value: false
Lr:
  desc: null
  value: 0.0001
ManageSymmetries:
  desc: null
  value: true
Periods:
  desc: null
  value:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
Pip:
  desc: null
  value: 3.1e-06
Pixels:
  desc: null
  value: 30
Render:
  desc: null
  value: false
Type:
  desc: null
  value: gadf
UpdateTimestamp:
  desc: null
  value: 90
ValueLossCoefficient:
  desc: null
  value: 0.5
WalletFactor:
  desc: null
  value: 1000000
_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1641035022
    t:
      1:
      - 1
      - 5
      3:
      - 16
      4: 3.7.6
      5: 0.12.6
      8:
      - 3
      - 5
